#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 26 22:01:34 2020

@author: Jens
"""

import numpy as np

class Action():
    pass

class ActionGroup():
    pass

class ProductAction():
    pass

class ProductActionCollection():
    pass

class States():
    pass

class ProductStates():
    pass

class TimeIndex():
    def __init__(self, time_range):
        self.time_range = time_range
        
    def forward(self):
        return np.arange(len(self.time_range))
        
    def backward(self):
        return  np.flip(self.forward())

class TimeRange():
    def __init__(self, start, end, freq=None):
        
        if freq is None:
            start_datetime = np.datetime64(start)
            end_datetime = np.datetime64(end)
        else:
            start_datetime = np.datetime64(start, freq)
            end_datetime = np.datetime64(end, freq)
            
        self.times = np.arange(start_datetime, end_datetime)
        
    @property
    def index(self):
        return TimeIndex(self)
    
    def __len__(self):
        return len(self.times)



time_range = TimeRange(start='2020-04-01T00', end='2020-04-02')

actions = [Action(), Action()]

prod_acts = ProductActionCollection.from_actions(actions)

for time_index in time_range.index.backward():
    for prod_act in 
    
    
    
    
    